addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.5")
addSbtPlugin("com.eed3si9n"  % "sbt-assembly" % "0.14.6")

//addSbtPlugin("io.get-coursier"           % "sbt-coursier"        % "1.0.3")
//addSbtPlugin("com.dwijnand"              % "sbt-travisci"        % "1.2.0")
//addSbtPlugin("com.typesafe.sbt"          % "sbt-git"             % "1.0.0")
//addSbtPlugin("com.jsuereth"              % "sbt-pgp"             % "1.1.2")
//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.11")
//addSbtPlugin("org.lyranthe.sbt"          % "partial-unification" % "1.1.2")

addSbtPlugin("se.marcuslonnberg"  % "sbt-docker"           % "1.5.0")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"         % "0.14.10")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"          % "0.5.0")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.3.7")
addSbtPlugin("com.thesamet"       % "sbt-protoc"           % "0.99.29")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"         % "1.5.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"              % "1.0.0")
addSbtPlugin("io.gatling"         % "gatling-sbt"          % "3.1.0")
addSbtPlugin("com.tapad"          % "sbt-docker-compose"   % "1.0.35")
